# Generated by Django 5.0.3 on 2024-03-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_category_remove_books_isbn_books_descriptiom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='book_genre', to='books.genre'),
        ),
    ]
