# Generated by Django 5.0.3 on 2024-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_tags_remove_books_categories_remove_books_genres_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='descriptiom',
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
